---
title: "cv"
format: html
---


# Yutian Du

**Ph.D. Student in Environment, Yale University**

Email: [yutian.du@yale.edu](mailto:yutian.du@yale.edu)  
Tel: 203-435-0996  
Yale School of the Environment, Yale University, 195 Prospect Street, New Haven, CT 06511, USA

## Research Interests

- Impacts and Mitigation of Climate Change
- Extreme Hydroclimatic Hazards
- Drought Propagation Mechanisms
- Plant Responses to Heat and Drought Stress
- Ecosystem Carbon Cycling
- Hydrological Modeling and Prediction

## Skills

- **Programming & Data Analysis:** Python, MATLAB, R, ArcGIS, CCM, OPGD, Google Earth Engine (GEE)
- **Hydrological Modeling:** SWAT, SPHY

## Education

- **Ph.D. in Environment**  Yale School of the Environment, Yale University | 2026 – Present
- **M.S. in Civil and Hydraulic Engineering**  North China University of Water Resources and Electric Power | 2022 - 2025
- **B.S. in Water Engineering**  North China University of Water Resources and Electric Power | 2018 - 2022  


## Research Experience

### North China University of Water Resources and Electric Power (NCWU)

**National Natural Science Foundation of China Project: "Evolution of Micro-topography and the Response of Fish Habitat in a Sediment-Laden River Downstream of a Reservoir"** |May 2024 – Aug 2024
**Water Resources Survey and Assessment Project** |Jul 2023 – Sep 2023
**Mountain Flood Hazard Analysis and Assessment Project** |Sep 2022 – Jun 2023

## Internship

**Hydrology and Water Resources Department, Nanjing Hydraulic Research Institute** |Oct 2023 – Apr 2024


## Publications

### 2025

#### Investigation into the temporal impacts of drought on vegetation dynamics in China during 2000 to 2022

**Yutian Du**, Subing Lv, Fuqiang Wang, Jie Xu, Heng Zhao, Lei Tang, Heng Wang, and Honglu Zhang  
*Scientific Reports*, **15**, 6351 (2025)

[DOI](https://doi.org/10.1038/s41598-025-90692-y)

---

#### Investigation into the supply-demand relationship of carbon sequestration in the Yellow River Basin using the optimal parameter geographical detector model

Heng Zhao, Yingying Gai, Fuqiang Wang, Lanbo Cui, **Yutian Du**, Heng Wang, Lei Tang, and Huan Yang  
*Scientific Reports*, **15**, 29079 (2025)

[DOI](https://doi.org/10.1038/s41598-025-15298-w)

### 2024

#### Study on the multi-type drought propagation process and driving factors on the Tibetan Plateau

Heng Wang, Heng Zhao, Fuqiang Wang, Bing Yan, Lei Tang, **Yutian Du**, and Lanbo Cui  
*Journal of Hydrology*, **645**, 132162 (2024)

[DOI](https://doi.org/10.1016/j.jhydrol.2024.132162)